openstack-k8s-operators/openstack-k8s-operators-ci

dockerfile_to_osbs.sh

In OSBS downstream versions of Dockerfile some ARGS must be
different from upstream versions. This script allows to set
or unset various args.
The idea is to have this script running in automated fashion
before final Dockerfile lands in the distgit, so:
Upstream Dockerfile -> dockerfile_to_osbs -> push to distgit ->
build OSBS image.

Script to set/unset Dockerfile ARGS

---

test-runner/golint.sh

In OpenShift CI $go get: disabled by -mod=vendor
Use of -mod=readonly is a work-around for the issue.

Use -mod=readonly for golint.

---

test-runner/golint.sh

Flag -mod=readonly is deprecated in go 1.14,
ensure it's used only on previous versions.

Fix golint logic to be go version aware

---

test-runner/golangci.sh
test-runner/gotest.sh
test-runner/govet.sh

Adding go mod vendor is required by OpenShift CI.

Add go mod vendor to three tests

---

test-runner/golint.sh

vendor should be skipped using golint, however this tool
does not allow to skip it, removing as it's just vendor
with deps.

Remove vendor folder from the golint command

---

test-runner/golangci.sh

golangci in OpenShift prow environment is trying to
create /.cache folder and that's not permitted due
to different user running the job.
Setting GOLANGCI_LINT_CACHE resolves the issue.

Add cache folder variable for golangci

---

test-runner/golangci.sh

golangci-lint is timing out occasionally, increasing
timeout from default 1m to 2m.

Increase golangci-lint timeout to 2m from 1m

---

dockerfile_to_osbs.sh

Dockerfile for osp director operator is slightly different
so the conversion script requires update.

Adjust osbs script to reflect osp director operator

---

stage_downstream_rebase.sh

osp-director-operator master branch should be used to build
rhosp-rhel8-tech-preview containers from downstream
rhos-16.2-rhel-8 branch.

Use master branch to build rhosp-rhel8-tech-preview images

---

test-runner/golangci.sh

This is triggering the OOMKiller in CI
https://golangci-lint.run/usage/performance/

Reduce golangci memory usage

---

test-runner/golint.sh

In go 1.17 'go get' was deprecated for installing executables. In
go 1.18 it is now required to use 'go install'.
This fixes the installation to use go install across the board
as all of our operators are now using go 1.17 or later.

Use 'go install' to install golint

---

.github/workflows/golangci-lint.yaml
test-runner/golint.sh
test-runner/gotest.sh
test-runner/govet.sh

Added a .github/workflow to test against OSP Director Operator. This should prevent us committing broken stuff here.
This also updates most of the test runners to remove vendoring which caused failures with golang 1.18.

Add .github workflows. Remove vendoring from test-runners

---

test-runner/gofmt.sh
test-runner/golangci.sh
test-runner/golint.sh
test-runner/gotest.sh
test-runner/govet.sh

Param $1 is used for the modules dir relativ to the repo root dir.
When passt before running the check commant it cd into MODULE_DIR,
runs command and returns. With this its possible to check different
modules from the make file passing the module dir.

Support passing modules dir to test-runner scripts

---

test-runner/golangci.sh

Default timeout of 2m can be to low depending on the repo size.
Lets set the default to 5m and allow passing custom timeout via
param $2.

Allow passing timeout to golangci.sh runner script

---

test-runner/golangci.sh
test-runner/golint.sh
test-runner/gotest.sh
test-runner/govet.sh

Some changes that should fix stable branch tests on OSPdO
but should still work with latest.

test runner updates for 1.17 (OSPdO)

---

.github/workflows/golangci-lint.yaml
test-runner/golint.sh

This avoids issues issues with deps getting updated when we run 'go get' in the projects go module. Should keep us from seeing test failures where unexpected dependencies creep in.

Install go lint in separate go.mod

---

.github/cluster_pre_steps.sh
.github/install_operator_with_hash.sh
.github/operators_post_tests.sh
.github/sno_heat_stack.yaml
.github/workflows/reusable-workflow-e2e.yaml

We are adding a reusable workflow for the e2e job for Pull request testing, this workflow will be used by other operators in openstack-k8s-operators organization.
In this workflow:-
* We build individual operator container images using PR content.
* Build openstack operator(passing the Individual Operator bundle image we build earlier)
* We start a SNO OCP cluster in an OpenStack cloud.
* Install operator on OCP cluster using meta operator.
* Do basic Service tests.
Apart from workflow, we are adding some basic shell scripts that will be consumed by the workflow.

Add reusable workflow for e2e test job

---

.github/workflows/reusable-workflow-e2e.yaml

Ci for PR coming from Depenandabot is failing with the below because of slashes in the branch name which Dependabot creates.
https://github.com/openstack-k8s-operators/keystone-operator/actions/runs/3444156331/jobs/5746524087#step:4:19
Before this patch, we replaced go.mod in openstack-operator with PR commit using the branch name.
ex:
~~~
go mod edit --replace
github.com/openstack-k8s-operators/keystone-operator/api@$version= github.com/ysandeep93/keystone-operator/api@dependabot/go_modules/ sigs.k8s.io/controller-runtime-0.13.1
~~~
After Go 1.13, there is a known issue if we have slashes in the branch name.[1]
~~~
$go mod tidy
go: errors parsing go.mod:
/tmp/openstack-operator/go.mod:97:
replace github.com/ysandeep93/keystone-operator/api: version …

Use Hash instead of Branch name to replace go.mod

---

.github/workflows/reusable-workflow-e2e.yaml

So far, we were using GITHUB_SHA in the heat stack name, GITHUB_SHA gives merged hash. In scenarios where we have parallel PR for same operator this could issue because heat stack with same name is already created.
~~~
ERROR: The Stack (gha_sno_stack_a148a37) already exists.
~~~
With this patch we are changing naming convention of stack to include operator name and PR number to avoid duplicate stack name.
New stack name example: gha_sno_stack_keystone-operator_2

Heat Stack name Optimization

---

test-runner/gofmt.sh
test-runner/golangci.sh
test-runner/golint.sh
test-runner/gotest.sh
test-runner/govet.sh

The cinder-operator patch [1] introduces the `go.work` file within the repository with the goal of automating the way we deal with multi module dependencies.
However, the side effect of having a versioned `go.work` in the repo is the failure of the `govet` CI script because `GOWORK` is automatically set to `on`. This patch fixes the CI run on the cinder-operator PR [1], introducing a `GOWORK` variable (which is set to off by default) to make sure we can successfully run this check regardless of the approach.
The `GOWORK` variable value is also inherited from the `Makefile` of the project.
[1] https://github.com/openstack-k8s-operators/cinder-operator/pull/79
Signed-off-by: Francesco Pantano <fpantano@redhat.com>

Add GOWORK variable to the CI scripts

---

.github/workflows/reusable-workflow-e2e.yaml

We tested reusable workflow in tripleo-ci org first, we missed to update this reference in the initial patch.

Checkout ci repo from openstack-k8s-operators org

---

images/build-root/Dockerfile

This patch adds a build root image that can be used on build and deploy jobs.

Add build root image to be used on CI

---

.github/workflows/reusable-workflow-e2e.yaml

Openstack-operator was upgraded to golang 1.19/SDK 1.26 in [1].
Since currently we use the reusable workflow only in keystone-operator. In this patch, I am updating the go-version / operator sdk for steps in which we build openstack operator, will bump in individual operator step when we bump keystone-operator to 1.19
[1]  https://github.com/openstack-k8s-operators/openstack-operator/pull/149

Upgrade to golang/sdk1.26

---

images/build-root/Dockerfile.custom

This patch adds a new custom Dockerfile that can be used to generate different tag, for different versions of golang, operator-sdk and kustomize.

Add build root custom Dockerfile

---

.github/workflows/golangci-lint.yaml
.github/workflows/reusable-workflow-e2e.yaml

The set-output workflow command was deprecated[1].
[1] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Signed-off-by: Takashi Kajinami <tkajinam@redhat.com>

Replace deprecated set-output workflow commend

---

images/tempest-container/Dockerfile

This patch adds the tempest-container Dockerfile to be build in our ci, instead of build it every time a job starts, this will save us some precious time running the job.

Add tempest-container Dockerfile

---

images/build-root/Dockerfile.custom

This patch adds a validation on binaries that are download during root image build.

Add validation to bins downloaded in root image

---

renovate.sh

The service operator repos all have `make tidy` targets now to run go mod tidy on both mod files in the repo. So to be able to use that in renovate this patch adds that command to the allow list.

[renovate]Allow running make tidy

---

renovate.sh

The operator CRD (OVS) was moved to ovn-operator (under OVNController name) and ovs-operator is no longer needed. We plan to archive the repo. This is in preparation to this action.

Remove ovs-operator from renovate script

---

renovate.sh

Now we are replacing dependabot by renovate in telemetry operator.

Run renovate for telemtry operator

---

renovate.sh

As we always pulling the latest renovate image we need to make sure that old images are cleaned otherwise we will run out of disk space regularly.

[renovate]Clean up old container images

---

renovate.sh

Until now renovate rebased its open PRs every hour if there was a new version from the dependency being bump or if there was a new change on the base branch of the PR. This is fairly wasteful for CI resources.
This change instructs renovate to only auto rebase the PRs during our weekend schedule when new PRs are also considered.
The user can still request rebasing a PR via the checkbox in the PR description.

Limit auto rebase of renovate PRs

---

.github/workflows/reusable-build-operator.yaml

Additional updates:
-update all github actions to latest
-fix build warnings
-inputs for golang version and operator_sdk version
-tag operator, bundle, and index images with a sha256 'digest', this
should help container images persist longer on quay.io
Jira: [OSP-29146](https://issues.redhat.com//browse/OSP-29146)

Add reusable workflow for building operators

---

.github/workflows/reusable-build-operator.yaml

Added a pushd into the github workspace directory to standardize the optional catalog_extra_bundles_script input parameter location.

Support the openstack-operator's index build

---

images/build-root/Dockerfile.custom

This is needed by the openstack-operator bundle builds which will soon require skopeo in order to execute 'make bundle'

Add skopeo to Dockerfile.custom

---

.github/workflows/reusable-build-operator.yaml
images/tempest-container/Dockerfile

golang 1.21 is pushed by default in latest ubuntu runner image[1] and with that openstack-operator index build fails, we need to force compatible golang version during index image builds too like it's done with bundle image builds.
[1] https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240225.1

Force go version during index build too

---

images/tempest-container/Dockerfile

Now that openstack-tempest-skiplist is retired, it is now available to install with openstack dependencies. This patch adds a manual installation based on the latest commit in this repo.

Manually install tempest-skiplist in tempest container

---

.pre-commit-hooks.yaml
pre-commit-hooks/kuttl-single-test-assert.sh

This pre-commit check ensures that no TestAsserts are defined in our kuttl tests that are ignored by kuttl.
This can be then used in the service operators by adding the following to the .pre-commit-config.yaml
```
- repo: https://github.com/openstack-k8s-operators/openstack-k8s-operators-ci
hooks:
- id: kuttl-single-test-assert
```

[pre-commit]Add shared kuttl pre-commit rules

---

renovate.sh

That operator is now merged to openstack-operator
Related: [OSPRH-7421](https://issues.redhat.com//browse/OSPRH-7421)

[renovate]remove dataplane operator

---

renovate.sh

Renovate script fails with:
```
Storing signatures
DEBUG: Using RE2 regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in config.js
DEBUG: No config file found on disk - skipping
error: unknown option '--log-file-level=debug'
```
This drops the parameter, the output still shows DEBUG messages.

Drop unknown option '--log-file-level=debug'

---

renovate.sh

It turned out that make force-dump alone is not enough. We need to git reset away what renovate did first to avoid leaking through transitive dependency bumps like k8s.io.
Related: [OSPRH-8355](https://issues.redhat.com//browse/OSPRH-8355)

Allow git reset as post task

---

images/build-root/Dockerfile.rhel-9.custom

Add yq to Dockerfile.rhel-9.custom

---

.github/workflows/reusable-build-operator.yaml

Lack of a go.sum generates a warning.
This go is not used to build the operator, so caching here will not speed up the build.

Disable setup-go module caching

---

renovate.sh

This extra env variable should allow 'make bindata' to git add new files (new APIs, etc) if they get pulled in during a promotion.

Renovate: set -e BINDATA_GIT_ADD=true

---

test-runner/golangci.sh

v2.0.0 was just release, which makes golangci to fail with the golang version used. This allows passing a release tag for the golangci version should be used.

Allow passing a release tag for golangci

---

.github/workflows/force-bump-branches.yaml
.github/workflows/force-bump-pull-request.yaml

This workflow calls force-bump and generates a pull request which should contain all the necissary updates to manifests. For openstack-operator bindata is also updated.
If no changes are detected no PR should get generated
Includes an additional force-bump-branches workflow which can be called via a schedule job in the operator repos to schedule PRs for all stable braches (main, fr2, etc) to be automatically generated on weekends.
Jira: [OSPRH-15737](https://issues.redhat.com//browse/OSPRH-15737)

Add force-bump-pull-request workflow

---

.github/workflows/force-bump-pull-request.yaml

It is already getting set locally on most release
branches so we didn't catch this. The intent
in setting BRANCH here is so we might
consider not having to update the Makefiles
in release branches with regards to this default

BRANCH should be supplied to force-bump, not bindata
