.travis.yml, README.md, deploy-on-quay.sh, openstack-k8s-builder-toolbox, preflight.sh
See below comments for details
=> Added Dockerfile and Travis automation

.travis.yml, README.md, deploy-on-quay.sh, preflight.sh
Changes include:
- Create unique "build" stage
- Build stage should only be run on merge to master per https://stackoverflow.com/questions/57387227/how-to-run-tests-on-pr-deploy-on-merge-with-travis-ci
=> Updated Travis CI workflow

.travis.yml
=> Ensure Travis builds only after merge to master

.travis.yml
Based on https://docs.travis-ci.com/user/conditions-v1
=> Modified Travis conditional syntax

openstack-k8s-builder-toolbox
=> Removed erroneous whitespace from Dockerfile

deploy-on-quay.sh, preflight.sh
- Changed how `git diff` is calculated in `preflight.sh` based on https://stackoverflow.com/questions/41145041/list-files-modified-in-a-pull-request-within-travis
- Added debug prints to `preflight.sh`
- Added comments to `deploy-on-quay.sh`
=> Updated shell scripts

openstack-k8s-builder-toolbox, preflight.sh
- Added newline to `preflight.sh`
- Added comment to `openstack-k8s-builder-toolbox`
=> Minor changes to preflight script and Dockerfile

test-runner/gofmt.sh, test-runner/golangci.sh
Adds gofmt and golangci test runners.
=> Add gofmt and golangci test runners

osbs_templates/container.yaml, osbs_templates/content_sets.yml
With the templates automatic generation of required files is
possible.
=> Add templates required by OSBS system

stage_downstream_rebase.sh
Work based on: https://github.com/openstack-k8s-operators/osp-director-operator/pull/397
Script has couple of simple options, use --help for more information.
=> File to help downstream rebases

stage_downstream_rebase.sh
Reverts openstack-k8s-operators/openstack-k8s-operators-ci#30
=> Revert "Use master branch to build rhosp-rhel8-tech-preview images"

test-runner/golint.sh
Until we make it work with both old and new projects
=> Revert recent golint updates

images/pre-commit/Dockerfile
Once we merge this Dockerfile we can validate if Prow image promotion can provide this image to other operator's repo.
=> Add a Dockerfile to be used on pre-commit jobs

renovate.sh
* https://github.com/openstack-k8s-operators/dataplane-operator/pull/121
* https://github.com/openstack-k8s-operators/openstack-ansibleee-operator/blob/main/renovate.json
=> Add dataplane-operator and openstack-ansibleee-operator to renovate

renovate.sh
Also cleanup duplicated references for
heat and horizon operator.
=> Run renovate for neutron, ovn and ovs operator

renovate.sh
Depends-On: https://github.com/openstack-k8s-operators/openstack-baremetal-operator/pull/31
=> Run renovate job for openstack-baremetal-operator

images/tempest-container/Dockerfile
... because TripleO is being deprecated.
=> Replace tripleo-repos by repo-setup

images/tempest-container/Dockerfile
'yq' will be used to edit some yaml files.
=> Add 'yq' to tempest image

.github/workflows/golangci-lint.yaml, renovate.sh
https://github.com/openstack-k8s-operators/openstack-operator/pull/1061
=> Drop AEE from renovate script

renovate.sh
Related: [OSPRH-8355](https://issues.redhat.com//browse/OSPRH-8355)
=> [renovate]Allow make force-bump as post update task

renovate.sh
This reverts commit 57599d86e314da729b4e231d604a4f5b8482f7be.
also moves log cleanup into the while loop
=> Revert "fix log delete find command"

.github/workflows/force-bump-branches.yaml, .github/workflows/force-bump-pull-request.yaml
Adds a token option to the force pull request action so we can configure a custom PAT for the pull request.
The motivation is to have the PRs get automatically approved for CI/test runs
=> Add token/secret to force pull request action

.github/workflows/force-bump-branches.yaml, .github/workflows/force-bump-pull-request.yaml, Dockerfile.build-tools, README-build-tools.md, build-tools-image.sh
- Add Dockerfile.build-tools with comprehensive tool suite:
* Go 1.21 toolchain for go.mod managed dependencies
* Pre-built binaries: kustomize v5.5.0, operator-sdk v1.31.0
* golangci-lint v1.59.1, kubectl-kuttl 0.17.0, yq, oc 4.16.0, opm v1.29.0
* System tools: jq, skopeo, file for script compatibility
* Tools installed in /tmp/workspace/bin and available via PATH
* Fixed curl-minimal conflicts using dnf swap
* Excluded go install tools (managed via go.mod dependencies)
- Add build-tools-image.sh script for easy container builds:
* Support for custom image names, tags, and registry push
* Command-line options with help documentation
* Default image: openstack-k8s-operators-ci-build-tools
- Complete force-bump-pull-request.yaml workflow integration:
* Use custom container image with …
=> Add CI build tools container with tool coverage
